#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleFix.Resource", IsApplication=true)]

namespace SimpleFix
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::SimpleFix.Resource.String.library_name;
			global::Implementation.Resource.Id.message = global::SimpleFix.Resource.Id.message;
			global::Implementation.Resource.Id.result = global::SimpleFix.Resource.Id.result;
			global::Implementation.Resource.Id.send = global::SimpleFix.Resource.Id.send;
			global::Implementation.Resource.Layout.RequestActivity = global::SimpleFix.Resource.Layout.RequestActivity;
			global::Implementation.Resource.String.Ok = global::SimpleFix.Resource.String.Ok;
			global::Implementation.Resource.String.button_send = global::SimpleFix.Resource.String.button_send;
			global::Implementation.Resource.String.edit_message = global::SimpleFix.Resource.String.edit_message;
			global::Implementation.Resource.String.library_name = global::SimpleFix.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int message = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int result = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int send = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RequestActivity = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Hello = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Ok = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int button_send = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int edit_message = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int library_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
